version: "3.9"

services:
  web:
    image: siailyadev/skb-front:latest
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: curl -sS http://127.0.0.1:3000 || echo 1
      interval: 30s
      timeout: 3s
      retries: 12
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

  auth:
    image: siailyadev/skb-auth:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - db
    healthcheck:
      test: curl -sS http://127.0.0.1:5000/api/auth/healthcheck || echo 1
      interval: 30s
      timeout: 3s
      retries: 12
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s

  db:
    image: postgres:13.2
    container_name: skb-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=skb123456789
      - POSTGRES_USER=skb
      - POSTGRES_DB=skb
    volumes:
      - skb-database:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - "node.role==manager"

volumes:
  skb-database:
    external: true
