version: "3.9"

services:
  web:
    build: skb-front/.
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./skb-front:/app

  auth:
    build: skb-auth/.
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - db
    networks:
      - postgres
    volumes:
      - ./skb-auth:/app

  db:
    image: postgres:13.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=skb123456789
      - POSTGRES_USER=skb
      - POSTGRES_DB=skb
    volumes:
      - ./docker-data/pgdata:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:6.13
    environment:
      PGADMIN_DEFAULT_EMAIL: "sia.ilya.dev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "skbPassword!2022"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./docker-data/pgadmin:/var/lib/pgadmin
    ports:
      - "7000:80"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
