name: Auth CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'skb-auth/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./skb-auth/
          push: true
          tags: siailyadev/skb-auth:latest

      - name: Invoke deployment Portainer hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          data: '{ "deploy": "true" }'
